#############################################################################
# Generated by PAGE version 4.12
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.lab38
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 616x486+1160+345
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1061
    wm minsize $top 120 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Enya -- Watermark"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent38 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent38" "pathtowimg" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Watermark Image} 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$top.but40" "browsewimg" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Folder to watermark} 
    vTcl:DefineAlias "$top.lab41" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent42" "pathtodir" vTcl:WidgetProc "Toplevel1" 1
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$top.but43" "browsewdir" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex46 \
        -background white -font TkTextFont -foreground black -height 354 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 304 -wrap word 
    .top37.tex46 configure -font TkTextFont
    .top37.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "printlog" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Log 
    vTcl:DefineAlias "$top.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $top.tPr48
    vTcl:DefineAlias "$top.tPr48" "progbar" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab38 \
        -foreground black -background {#d9d9d9} -height 215 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 220 
    vTcl:DefineAlias "$top.lab38" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab38
    checkbutton $site_3_0.che39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che39 
    vTcl:DefineAlias "$site_3_0.che39" "placetopleft" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che40 
    vTcl:DefineAlias "$site_3_0.che40" "placetopcenter" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che41 
    vTcl:DefineAlias "$site_3_0.che41" "placetopright" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che42 
    vTcl:DefineAlias "$site_3_0.che42" "placeleft" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che43 
    vTcl:DefineAlias "$site_3_0.che43" "placebottomleft" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che44 
    vTcl:DefineAlias "$site_3_0.che44" "placebottomcenter" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che45 
    vTcl:DefineAlias "$site_3_0.che45" "placebottomright" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che46 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che46 
    vTcl:DefineAlias "$site_3_0.che46" "placeright" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -variable che47 
    vTcl:DefineAlias "$site_3_0.che47" "placecenter" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.che39 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.che40 \
        -in $site_3_0 -x 100 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.che41 \
        -in $site_3_0 -x 180 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.che42 \
        -in $site_3_0 -x 10 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.che43 \
        -in $site_3_0 -x 10 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che44 \
        -in $site_3_0 -x 100 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che45 \
        -in $site_3_0 -x 180 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che46 \
        -in $site_3_0 -x 180 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.che47 \
        -in $site_3_0 -x 100 -y 100 -anchor nw -bordermode ignore 
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Where to place watermark} 
    vTcl:DefineAlias "$top.lab48" "Label4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Start 
    vTcl:DefineAlias "$top.but53" "start" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent38 \
        -in $top -x 10 -y 40 -width 174 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 0 -y 10 -width 129 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 200 -y 40 -width 57 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x -10 -y 70 -width 167 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent42 \
        -in $top -x 10 -y 100 -width 174 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 200 -y 100 -width 57 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 280 -y 40 -width 304 -relwidth 0 -height 354 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 390 -y 10 -width 66 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tPr48 \
        -in $top -x 20 -y 440 -width 560 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab38 \
        -in $top -x 10 -y 180 -width 220 -relwidth 0 -height 215 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 10 -y 150 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 380 -y 400 -width 77 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

